apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    prometheus-monitored: "true"
spec:
  selector:
    app: scaletestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort